- hosts: insta_server
  become: true
  gather_facts: false  
  vars_files:
    - ./group_vars.yml
  tasks: 
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
     update_cache: yes
  - name: Ansible shell module multiple commands
    shell: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
  - name: Install reqired packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - curl
      - wget
      - nginx
      - nodejs
# PM2 is a production process manager for Node.js applications,keep applications alive forever, to reload them without downtime
  - name: Install PM2 globally
    npm:
      name: pm2
      global: yes

  - name: Clone a private repository
    git:
     repo: "{{ git_repo_url }}"
     dest: "{{ repo_path }}"
     version: "{{ repo_branch }}"
     update: yes
     accept_hostkey: yes
  - name: Install node-modules in  client
    npm:
      path: "{{ repo_path }}/client"
      state: present
  - name: Install node-modules in  server
    npm:
      path: "{{ repo_path}}/server"
      state: present
  - name: Build app
    command: npm run build
    args:
      chdir: "{{ repo_path }}/client"
  - name: start pm2 process
    command: 'pm2 start npm --name "insta_clone" -- start'
    args:
      chdir: "{{ repo_path }}/client"


